= Bounty

[%hardbreaks]
Pour 30 bounty
Temps total : 12 h 50 min &nbsp;&nbsp;&nbsp;&nbsp; (préparation : 40 min / cuisson : 10 min / repos : 12 h)

== Ingrédients

[%hardbreaks]
1 boîte de lait concentré sucré (environ 400 g) (Nestlé)
200 g de noix de coco rapée (assez grosse)
300 g de chocolat noir ou chocolat au lait pâtissier

== Etapes

. Mélangez dans un saladier le lait concentré et la noix de coco râpée.
. Etalez ce mélange sur 2 cm d’épaisseur dans un moule carré (ou sur une plaque) recouvert de papier cuisson.
. Recouvrez d’un film alimentaire et placez au frigo une nuit.
. Le lendemain sortez du réfrigérateur et découpez en rectangle.
. Façonnez les rectangles avec les doigts pour obtenir une jolie forme arrondie.
. Placez 30 min au congélateur pour durcir la pâte.
. Dans un bol faites fondre le chocolat au bain-marie ou au four à micro-onde en mélangeant toutes les 30 secondes.
. Sortez les barres coco du congélateur. A l’aide d’une fourchette attrapez une barre coco, trempez-la dans le chocolat fondu. Recouvrez bien de chocolat, rattrapez la barre avec la fourchette, tapotez pour ôter l’excédent de chocolat et raclez la fourchette sur le rebord du bol. Posez délicatement sur une feuille de papier cuisson. Déposez la fourchette sur la barre chocolatée pour la marquer.
. Recommencez pour toutes les barres coco.
. Placez les barres coco choco au frais jusqu’à ce que le chocolat soit durci.

== Informations

[%hardbreaks]

== Liens

[%hardbreaks]
https://odelices.ouest-france.fr/recette/barre-chocolatee-noix-coco-facon-bounty-maison-r4106/
