= Cheesecake Soufflé

[%hardbreaks]
Pour 6 personnes
Temps total : 1 h 40 min &nbsp;&nbsp;&nbsp;&nbsp; (préparation : 20 min / cuisson : 1 h 20 min)

== Ingrédients

[%hardbreaks]
160 g de fromage frais (Philadelphia)
20 g beurre
50 ml de lait
40 g de farine boulangère (T55) (ou 30 g de farine et 10 g d'amidon)
4 oeufs
1/4 de cuillère à déssert de jus de citron
80 g de sucre
Confiture ou miel

== Etapes

. Ecraser le fromage dans le récipient à bain-marie
. Faire fondre le fromage et le beurre au bain-marie jusqu'à obtenir un mélange homogène (à la spatule)
. Ajouter le lait et mélanger jusqu'à obtenir un mélange homogène (à la spatule)
. Retirer la préparation du bain-marie
. Ajouter la farine et mélanger jusqu'à obtenir un mélange homogène (à la spatule)
. Ajouter les jaunes d'oeufs et mélanger jusqu'à obtenir un mélange homogène (à la spatule)
. &nbsp;&nbsp;&nbsp;&nbsp;Allumer le four à 170/180°C (15 min minimum)
. Battre les blancs d'oeufs avec le citron en neige (avec les pointes molles). Dès l'apparition des grosses bulles, ajouter 1/3 du sucre et attendre 15 s (Répéter 3 fois)
. &nbsp;&nbsp;&nbsp;&nbsp;Chauffer l'eau pour le bain-marie
. Ajouter 1/6 des blancs en neige dans la prépartion au fouet (1 seul sens de rotation)
. Ajouter 1/6 des blancs en neige dans la prépartion à la spatule (1 seul sens de rotation)
. Ajouter la préparation dans le reste des blancs en neige et mélanger à la spatule (1 seul sens de rotation)
. Découper un papier sulfurisé à la forme du moule à soufflés pour couvrir tout le fond
. Verser la préparation dans le moule à soufflés
. Verser l'eau bouillante dans un grand plat pour le bain-marie (qui ira au four)
. Placer le moule à soufflés au centre du bain-marie et mettre le tout au four
. Cuire 20 min à 160°C
. Ouvrir la porte du four 10s (pour évacuer la vapeur)
. Cuire 1 h à 100°C
. Démouler rapidement sur une assiette (en passant un couteau autour du cheesecake)
. Napper de confiture ou de miel

== Informations

Plat à soufflés (21 cm de diamètre, 10 cm de haut)
