= Cheesecake

[%hardbreaks]
Pour 8 personnes
Temps total : 6 h 35 min &nbsp;&nbsp;&nbsp;&nbsp; (préparation : 15 min / cuisson : 1 h 20 min / repos : 5 h)

== Ingrédients

=== Base biscuitée

[%hardbreaks]
125 grammes de biscuits secs type "galettes bretonnes"
55 grammes de spéculoos
80 grammes de beurre doux

=== Appareil à cheesecake

[%hardbreaks]
600 grammes de Philadelphia fromage frais
300 grammes de crème fraîche épaisse entière 33 % MG minimum
160 grammes de sucre en poudre
40 grammes de farine T45
5 oeufs
1/2 citron jus + zestes

== Etapes

. Emietter les biscuits (avec un mixeur). Fondre le beurre (au micro-ondes) et le verser sur les biscuits. Bien mélanger à la fourchette.
. Tapisser une plaque perforée d'une feuille d'aluminium puis au dessus déposer une feuille de papier sulfurisé. Poser au dessus un cercle haut de 20 cm de diamètre. Rabattre les bords des feuilles sur le moule pour bien l'emballer.
. Verser au fond le mélange biscuité et bien tasser.
. Placer la plaque au réfrigérateur.
. Préchauffer le four à 180°c, chaleur tournante.
. Dans le bol du robot, mettre le Philadelphia, la crème, le sucre, la farine et les oeufs. Mélanger avec la feuille vitesse lente (pas au fouet, il ne faut pas incorporer d'air afin que le cheesecake ne fissure pas à la cuisson !). Quand le mélange est lisse, ou presque (on ne mélange pas longtemps et il peut rester des petits morceaux de Philadelphia), arrêter de mélanger et ajouter les zestes et le jus du demi-citron. Continuer à mélanger avec le feuille doucement, juste pour bien répartir le citron.
. Sortir la plaque du réfrigérateur, verser l'appareil à cheesecake et enfourner 20 minutes à 180°c, puis baisser la température à 100°c et poursuivre la cuisson pour 60 minutes.
. A la fin de cuisson, ouvrir le four et laisser tiédir 15 minutes. Puis glisser délicatement le cercle avec le papier sulfurisé et l'aluminium sur un plat (je m'aide d'une grande spatule). Placer immédiatement au réfrigérateur pour 2 heures.
. Après 2 heures, retirer le papier aluminium et le papier sulfurisé délicatement en faisant glisser.
. Avec une fine lame de couteau trempée dans un verre d'eau tiède, décoller le cercle du cheesecake.
. Replacer au frais minimum 3 heures.
. Servir frais avec un coulis de fruits rouges.

== Informations

=== Pour que le cheesecake ne fissure pas, 2 points importants :
- on ne travaille pas trop l’appareil à cheesecake : il ne faut pas incorporer d’air. Donc pas de fouet ici !
- la cuisson se fait en 2 temps : à 180°c pendant 20 minutes puis on baisse la température à 100°c pour 60 minutes.

=== Comment démouler le cheesecake ?

C’est l’étape délicate, mais pourtant simple quand tout est bien préparé en amont. D’abord, utilisez un moule à charnière ou un cercle pour réaliser ce gâteau. Il faudra que le fond biscuité repose sur une feuille de papier sulfurisé pour le décoller facilement (on retirera la feuille on la glissant délicatement). Aussi, il faudra attendre qu’il soit refroidi avant de le retirer du cercle ou d’ôter la charnière. Pour retirer le cercle facilement il suffit de passer une fine lame de couteau trempée dans de l’eau chaude entre le cheesecake et le cercle ou la charnière. Vous verrez que de cette manière c’est facile et on n’abime pas le gâteau. On pourra même lisser le bord du cheesecake avec la lame du couteau.

== Liens

[%hardbreaks]
https://www.yumelise.fr/cheesecake-new-yorkais/
