= Clafoutis grand-mère aux cerises

[%hardbreaks]
Pour 8 personnes
Temps total : 40 min &nbsp;&nbsp;&nbsp;&nbsp; (préparation : 10 min / cuisson : 30 min)

== Ingrédients

[%hardbreaks]
40 g de beurre demi-sel (+20g pour le moule)
100 g de farine
1 pincée de sel
600 g de cerises fraîches ou surgelées
4 oeufs
20 cl de lait
60 g de sucre en poudre
1 sachet de sucre vanillé
sucre glace

== Etapes

. Préchauffez le four à 210°C (thermostat 7)
. Lavez rapidement les cerises sous un filet d'eau fraîche, équeutez-les et égouttez-les. Personnellement j'enlève les noyaux, mais la recette traditionnelle veut qu'on les laisse, donc c'est à vous de voir si vous les laissez ou pas...
. Faites fondre les 40 g de beurre dans une petite casserole à fond épais
. Mélangez dans un grand bol la farine, le sucre, le sel et le sucre vanillé
. Incorporez les oeufs
. Incorporez le lait petit à petit en continuant de mélanger
. Ajoutez le beurre fondu
. Beurrez grassement le plat, rangez les cerises puis versez la pâte à clafoutis
. Mettez au four pendant 10 mn à 210°C
. Puis baissez à 180°C et cuisez encore 20 mn
. Servez le clafoutis froid ou tiède, saupoudré de sucre glace.

== Informations

[%hardbreaks]

== Liens

[%hardbreaks]
https://www.marmiton.org/recettes/recette_clafoutis-grand-mere-aux-cerises_29896.aspx
