= Crèmes brulées

[%hardbreaks]
Pour 4 personnes
Temps total : 4 h 30 min (minimum) &nbsp;&nbsp;&nbsp;&nbsp; (préparation : 15 min / pose infusion : 1 h / pose frigo : 2 h minimum / cuisson : 1 h 15 min)

== Ingrédients

[%hardbreaks]
50 cl de crème fleurette
70 g de sucre blanc en poudre
5 jaunes d'oeufs
1 gousse de vanille
60 g de cassonade

== Etapes

. Faire bouillir la moitié de la crème avec la gousse de vanille fendue et raclée à la casserole à feu doux
. Laisser reposer 1 h
. Faire bouillir une nouvelle fois à feu doux
. Faire blanchir les jaune avec le sucre au fouet dans un saladier
. Incorporer l'autre moitié de crème (froide) et bien mélanger
. Ajouter la crème bouillie encore chaude et bien mélanger
. Laisser reposer au frigo au moins 2 h dans un bol couvert
. Préchauffer le four à 95°C
. Répartir délicatement la préparation dans 4 petits plats en remuant le moins possible (répartir la fin dans les 4 plats car la vanille a tendance à se déposer)
. Cuire 1 h 15 min (consistance tremblante juste prise)
. Réserver au réfrigérateur (une nuit ?)
. Au moment de servir saupoudrer de cassonade, ajouter éventuellement un alcool, et faire caraméliser au chalumeau

== Informations

[%hardbreaks]
Bol en verre avec couvercle en plastique
4 Plats à oreilles / 4 plats à crème brulée
La vanille peut-être remplacée par des noix ou noisette moulues très fines
