= Galette des Rois

[%hardbreaks]
Pour 8 personnes
Temps total : 3 h 15 min &nbsp;&nbsp;&nbsp;&nbsp; (préparation : 25 min / repos : 2 h / cuisson : 50 min)

== Ingrédients
=== Frangipane
[%hardbreaks]
2 pâtes feuilletées (minimum 28 cm)
150 g de beurre mou
75 g d'amandes émondées
75 g d'amandes non émondées
150 g de sucre
3 + 1 oeufs
1 cas d'extrait de vanille (ou 1 gousse de vanille)
1 cas de rhum ambré
1 fève

=== Sirop
[%hardbreaks]
50 g de sucre
50 g d'eau
1 cas de rhum ambré

== Etapes
=== Frangipane
. Découper 2 cercles de 28 cm dans les pâtes et réserver au frais
. Réduire les amandes en poudre (grossière) au mixeur à 4 lames
. Dans un saladier, travailler le beurre en pommade à la spatule
. Ajouter le sucre et les graines de vanille (si pas d'extrait) et mélanger à la spatule
. Ajouter les 3 oeufs un par un en mélangeant au fouet
. Ajouter la poudre d'amande et mélanger à la spatule
. Ajouter l'extrait de vanille (si pas de gousse) et le rhum et mélanger à la spatule
. Sortir un cercle de pâte, humidifier les bords avec de l'eau et un pinceau sur 2 cm
. Garnir avec la préparation
. Sortir le 2nd cercle de pâte et recouvrir le tout avec
. Souder les bords au doigts en appuyant fort
. Chiqueter le bord de la galette
. Battre un oeuf et dorer la galette une 1ère fois au pinceau (pas sur les bords) (garder l'oeuf restant)
. Laisser reposer 2 h au frigo
. Allumer le four à 200 °C
. Dorer la galette une 2nde fois (pas sur les bords)
. Décorer avec le dos d'un couteau (sans percer la pâte)
. Piquer à plusieurs endroits sur le dessus pour faire de petites cheminées (pas au centre)
. Enfourner à 200 °C pendant 20 min
. Réduire la température à 180 °C et laisser cuire pendant 30 min (éventuellement protéger le dessus avec un papier aluminium pour les 15 dernières minutes)

=== Sirop
. Mélanger l'eau et le sucre dans une casserole et porter à ébullition
. Laisser refroidir un peu
. Ajouter le rhum
. Badigeonner la galette à la sortie du four avec un pinceau

== Informations

[%hardbreaks]

== Liens

[%hardbreaks]
https://www.youtube.com/watch?v=aiR8uFyxwzE
