= Gâteau Fondant à la Ricotta & au Chocolat

[%hardbreaks]
Pour 8 personnes
Temps total : 35 min &nbsp;&nbsp;&nbsp;&nbsp; (préparation : 10 min / cuisson : 25 min)

== Ingrédients

[%hardbreaks]
200 g de chocolat noir pâtissier
2 cuillères à soupe de lait
3 œufs (j’en avais que 2 bio)
250 g de ricotta
100 g de farine
100 g de sucre
1 sachet de levure
1 sachet de sucre vanillé
1 pincée de sel

== Etapes

. Préchauffer le four à 180°C.
. Fais fondre le chocolat avec les deux cuillères à soupe de lait au bain-marie ou au micro-ondes à puissance maximale deux fois 30 secondes en mélangeant bien pour avoir une ganache lisse .
. Dans un saladier, battre les œufs avec le sucre et le sucre vanillé jusqu’à ce que le mélange blanchisse et devient mousseux.
. Ajouter la ricotta et mélanger bien à l’aide d’un fouet ou une spatule .
. Incorporer la farine et la levure.
. Ajouter enfin le chocolat et la pincée de sel et mélanger bien.
. Verser la préparation à gâteau dans un moule à gâteau de 25 cm de diamètre beurré et fariné ou en silicone, lisser la surface puis enfournez pour 20 à 25 minutes de cuisson .
. Vérifier la cuisson avec la lame d’un couteau , elle doit ressortir propre .

== Informations

[%hardbreaks]
Moule en verre : 24 cm x 19 cm x 7.5 cm

== Liens

[%hardbreaks]
https://www.auxdelicesdupalais.net/gateau-fondant-a-la-ricotta-au-chocolat.html
