= Tajine d'agneau aux olives et citron

[%hardbreaks]
Pour 4 personnes
Temps total : 2 h 30 min &nbsp;&nbsp;&nbsp;&nbsp; (désossement et dégraissage épaule : 30 min / préparation : 20 min / cuisson : 1 h 30 min)

== Ingrédients

[%hardbreaks]
700g d'agneau
1 oignon (plutôt 1 jaune et 1 rouge)
2 gousses d'ail
1 bocal d'olives vertes (et/ou olives noires)
2 citrons confits (à défaut 1 citron jaune frais)
1 tomate
1 brocoli
(1 poivron rouge)
1 cac de gingembre
1 cac de cumin
1 cac de paprika
1 cas de persil
1 cac de safran (plutôt curcuma)
3 cas d'huile
sel, poivre

== Etapes

. Epluchez et hachez l'oignon.
. Pelez et écrasez l'ail.
. Coupez la viande en morceaux.
. Faites chauffer l'huile d'olive dans un tajine.
. Faites revenir l'oignon, l'ail et la viande.
. Ajoutez le sel, le gingembre et le safran (ou le curcuma).
. Couvrez d'eau et laissez cuire.
. Pendant ce temps, faites bouillir les fleurons de brocoli et les olives dans une casserole d'eau bouillante pendant 5 minutes.
. Egouttez et réservez.
. Nettoyez et coupez la tomate en quartiers.
. Egouttez et coupez les citrons confits en rondelles (ou le citron frais en 6 quartiers).
. Incorporez dans le tajine les fleurons de brocoli, les olives, le cumin, le paprika, le persil, les tomates et les citrons confits.
. Couvrez et laissez cuire.
. Dégustez chaud.

Astuces
Pour cette recette de Tajine d'agneau aux olives et citron, vous pouvez compter 20 minutes de préparation.

== Informations

[%hardbreaks]

== Liens

[%hardbreaks]
https://www.cuisineaz.com/recettes/tajine-d-agneau-aux-olives-et-citron-79968.aspx
