= Baguettes de pain

[%hardbreaks]
Pour x personnes
Temps total : xx min &nbsp;&nbsp;&nbsp;&nbsp; (préparation : xx min / cuisson : xx min)

== Ingrédients

[%hardbreaks]
ingredient1
ingredientx

== Etapes

. etape1
. etapex

== Informations

[%hardbreaks]




HOW TO MAKE CRUSTY FRENCH BAGUETTES

Transport yourself to your favourite bakery by making these incredible crusty baguettes and learn how to create the perfect CRUNCH using your oven at home. Master baker Anthony Silvio is back sharing all his tips on how to make your baguette with a chewy interior and the most divine, crispy golden crumb.

Watch How to Make CRUSTY FRENCH BAGUETTE video recipe:

How to Make CRUSTY FRENCH BAGUETTE like a Baker

crusty baguette

INGREDIENTS

Poolish (Pre-fermented dough)

190g/6.7oz Bakers Flour

190g/6.07oz Cool Water

Tiny pinch dried yeast

 

Final Dough

380g/13.4oz Bakers Flour

215g/8.8oz Cool Water

2g/.07oz Dried Yeast

10g/.35oz Sea Salt

10g/.35oz Diastatic Malt Powder (optional)

380g Poolish (made ahead of time)
Extra virgin olive oil
3-5 tblsp water in a glass

UTENSILS

2 x mixing Bowls
Kitchen bench or board
Tablespoon
Bowl scraper
Scale
Baking tray x 2
Linen cloth
Baking stone

 

METHOD

 Crusty french baguettes start with a pre-fermented dough, for crusty baguettes, we make poolish.

    Add a tiny pinch of dried yeast to a bowl of cold water before adding all the flour and mixing
    with a spoon.
    The mixture will start to resemble a paste, continue until it is combined well, then cover (tightly) with plastic wrap and leave to ferment at room temperature for 12-18 hours.

ANTHONY’S TIP: On warm days it will ferment quicker, on cooler days it will ferment slower, so just keep an eye on it.

    To make the crusty baguette dough, add the poolish to a bowl of cool water.
    Next, add the yeast, malt, flour and finally, salt.

ANTHONY’S TIP: The salt should always be added last on top of the flour so it doesn’t come into direct contact with the yeast because it will stop it from being active.

    Mix the crusty french baguette ingredients until they are combined and the flour is well hydrated.
    Cover with plastic wrap and leave to rest at room temperature for 15 minutes – don’t skip this step, it will help make the dough much easier to work with while it allows the flour to continue to hydrate.
    Wet your hands and remove the crusty baguette dough from the bowl (either using your hands or a bowl scraper).
    Before mixing the dough, dampen your hands using water as this will help to prevent it sticking from your board or bench.
    To mix the crusty baguette dough, scoop it off the bench, lifting it from one side then slap the dough forward, pull at it, then fold it all the way over to the top.
    Now pick the dough up from one side using both your hands and once lifted return back to the starting position, slap it down and fold over again.
    Repeat this “slap and fold” technique to work the dough until elastic and to help develop the gluten.

ANTHONY’S TIP: To check whether the dough has been worked enough, pull at a piece of it from the top and stretch it out. If holes aren’t created when you do this and it looks like a shiny, thin windowpane, it is ready.

    Create a ball with the crusty baguette dough by keeping it on your bench and rolling it gently using one hand then the other, pushing up against it over and again until it is tight and plump.
    Lightly grease a mixing bowl using extra virgin olive oil by adding a drizzle and then rubbing it around the bowl with your hand.
    Cover with plastic wrap and bulk ferment for 2 hours at room temperature.
    After one hour, uncover your dough and with a slightly damp hand, come underneath the dough to pick it up from one side then stretch and fold it over itself.
    Turn the bowl 90° and repeat this step, and again 2 more times before tucking in the bottom and turning the bowl as you go. This process will reinforce the gluten development in the dough.
    Cover with plastic wrap one more time and leave for one final hour.
    Gently tip your crusty baguette dough onto the bench and divide it into 200g pieces.
    To pre-shape the pieces of dough, stretch then fold, just like you did previously and make sure you then tighten each one by rounding them off pushing the ball from one side to the other before leaving to rest for 10-15 minutes.
    Lightly dust the bench (and your hands) with flour then get one piece of dough and place it upside down.
    Flatten slightly using the tips of your fingers then pick it up, stretch it out gently and place it down on the bench.
    Next, take the top of the dough and fold it over (towards yourself) approx. 2/3 of the way down using a small amount of pressure with your fingers on the edges making sure the dough sticks.
    Turn the crusty baguette dough 180° and repeat step 23.
    Now the dough will be long and no longer resemble a ball. Lift it off the bench, remove any excess flour, place it back down and start to roll it using your hands.
    Apply pressure on the ends only so that you create the tapered edges of a crusty baguette.
    Lay a linen cloth over the top of a baking tray, dust it with flour generously then pick up the dough and place it upside down on top of the cloth.
    Pull some linen up next to the crusty baguette dough and place another one next to it then repeat, placing each one snug against each other, seam side up, so that they don’t end up sticking to each other and hold their shape without going flat.
    Sprinkle some extra flour on top then cover the dough completely with another cloth so the dough doesn’t dry out.
    Leave to proof for 1 hour.

ANTHONY’S TIP: The proofing may take a little less or a little more time depending on the temperature of the day, so adapt to the conditions!

    At least half an hour before baking, pre-heat your oven to 240°C on the conventional setting and place a baking stone and dish/tray for steaming in the oven next to each other.
    When your baguettes are fully proofed they should spring back gently to the touch.
    Flour a flat tray (or pizza peel) and gently place your baguettes, seam side down (so turn them), onto this for easy and safe movement into the oven. Dust with some more flour.
    Use a baker’s lame to slash the baguettes, not cutting too deep and making sure that each cut overlaps the next cut.
    Slide the crusty baguette dough off the tray onto the hot baking stone in the oven.
    Pour a little water onto the hot preheated dish/tray and immediately close the oven door to capture as much steam as possible – this is the key to making the baguette CRUNCHY!
    Bake for 10 minutes then remove the dish/tray from the oven and bake for another 10-15 minutes or until well browned/golden and crusty.

crusty baguette recipe

Enjoy your CRUSTY FRENCH BAGUETTE

how to make baguette

HOW TO SERVE:

Allow to cool on a wire rack so the crumb inside can set then enjoy on its own, with some extra virgin olive oil or your favourite sandwich fillings.

french baguette

E ora si mangia, Vincenzo’s Plate…Enjoy!!!


https://www.vincenzosplate.com/recipe-items/crusty-french-baguette/
