= Gyozas

[%hardbreaks]
Pour x personnes
Temps total : xx min &nbsp;&nbsp;&nbsp;&nbsp; (préparation : xx min / cuisson : xx min)

== Ingrédients

=== Pâte
[%hardbreaks]
200 g de farine
2 g de sel
110 ml d'eau

=== Farce
[%hardbreaks]
400 g d'épaule de porc
300 g de crevettes crues
200 g de chou
15 g d'oignons verts (ou de poireau)
1/2 cuillère à soupe d'ail
1/2 cuillère à soupe de gingembre
1 cuillère à soupe de seasonning powder (ou bouillon de légume / volaille)
1 cuillère à soupe de sauce soja
1/2 cuillère à soupe d'huile de sésame
1/4 cuillère à soupe de poivre noir
Farine (pour étaler la pâte)
Huile (pour la cuisson)

=== Sauce
[%hardbreaks]
2 cuillères à soupe de sauce soja
1 cuillères à soupe de vinaigre de riz
2 cuillères à café de sauce chili
Graines de sésame

== Etapes

=== Pâte
. Tamiser la farine et le sel
. Ajouter l'eau et mélanger
. Pétrir pendant 2 min
. Faire reposer 15 à 20 min
. Pétrir pendant 5 min
. Faire reposer 1 heure en couvrant

=== Farce
. Hacher le porc le plus fin possible (hachoir)
. Eplucher les crevettes, les vider et les hacher le plus fin possible
. Dans un grand bol mélanger le porc, les crevttes, l'ail et le gingembre
. Mettre le chou dans un autre grand bol et couvrir d'eau bouillante
. Quand le chou est ramolli (environ 30s), l'émincer en petits morceaux et l'ajouter au mélanger
. Emincer les oignons verts et les ajouter au mélange
. Ajouter la sauce soja, l'huile de sésame, le poivre et bien mélanger pour avoir une belle farce homogène
. Séparer la pâte en 2 et rouler chaque partie en cylindre. Couper en morceaux de 8 à 10 g
. Fariner le plan de travail et former des cercles avec la pâte à l'aide d'un rouleau à patisserie (du bord vers le centre, pivoter, répéter)
. Placer un peu de farce au centre d'un cercle de pâte, fermer la pâte en chausson et replier la partie du dessus en faisant des plis vers le centre en partant du centre (2 côtés) pour fermer le gyoza
. Mettre de l'huile dans une poelle et faire chauffer (150°C)
. Placer les gyozas dans poelle et cuire à feu moyen pendant 2 min (le dessous doit être grillé / doré)
. Une fois bien dorés, verser 100 ml d'eau chaude et courvrir immédiatement pendant 5 min (jusqu'à évaporation) à feu moyen.
. Une fois toute l'eau absorbée cuire 2 min à découvert et retirer du feu

=== Sauce
. Pilonner les graines de sésame
. Mélanger tous les ingrédients

== Informations

[%hardbreaks]

== Liens

[%hardbreaks]
