= Titre

[%hardbreaks]
Pour 2 personnes
Temps total : xx min &nbsp;&nbsp;&nbsp;&nbsp; (préparation : xx min / cuisson : xx min)

== Ingrédients

[%hardbreaks]
2 belles côtelettes d’agneau
3 gousses d’aïl
1 oignon rouge
1 pointe de cannelle
1 pointe de gingembre en poudre ou râpé
1 poignée de pistaches
1 cuillère à soupe de miel liquide
1 pointe de piment d’espelette
1 cuillère à soupe d’huile d’olive
1 cuillère à soupe de tamari bio (sauce soja japonaise sans gluten)
1 boîte de 400g de pois chiches bio
1 boîte de 400g de haricots verts bio

== Etapes

. Epluchez et dégermez l’oignon et l’aïl. Emincez le premier et coupez le second en petits dés.
. Dans une sauteuse, faites-les dorer dans l’huile d’olive chaude. Faites ensuite dorer les côtelettes d’agneau des deux côtés. Ajoutez ensuite la cannelle, le gingembre, le piment d’espelette, le miel, le tamari et les pistaches. Remuez délicatement.
. Couvrez d’eau à hauteur, portez à ébullition et faites mijoter pendant une vingtaine de minutes, à feu moyen.
. Ajoutez dans la sauteuse les pois chiches et les haricots verts égouttés. Laissez cuire encore quelques minutes. Servez bien chaud.

== Informations

[%hardbreaks]

== Liens

[%hardbreaks]
https://www.gourmicom.fr/recette-tajine-agneau-gingembre-miel/
